about/urls.py
from . import views
from django.urls import path, include

app_name='about'

urlpatterns = [
    path('', views.aboutus_list, name='about')
]

blog/urls.py
from . import views
from django.urls import path

app_name='blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:id>', views.post_detail, name='post_detail'),
    path('category=<slug:category>', views.post_by_category, name='post_by_category'),
    path('tags=<slug:tag>', views.post_by_tag, name='post_by_tag'),
]

contact/urls.py
from django.urls import path
from . import views

app_name='contact'

urlpatterns = [
    path('', views.send_email, name='contact'),
    path('success/' , views.send_success , name='send_success'),
]

logisticexpress/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('contact/' , include('contact.urls' , namespace='contact')),
    path('about/', include('about.urls', namespace='about')),
    path('' , include('home.urls' , namespace='home')),
    path('services/', include('services.urls', namespace='services')),
    path('summernote/', include('django_summernote.urls')),    
]



urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "LOGISTICEXPRESS ADMIN"
admin.site.site_title = "LOGISTICEXPRESS ADMIN"
admin.site.site_index_title = "Welcome to LOGISTICEXPRESS ADMIN"

services/urls.py
from . import views
from django.urls import path, include

app_name='services'

urlpatterns = [
    path('', views.services, name='services')
]

templates/base.html
{% load static %}
<!doctype html>
<html class="no-js" lang="zxx">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>LOGISTICSEXPRESS </title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="manifest" href="site.webmanifest">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/img/favicon.ico' %}">

    <!-- CSS here -->
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/slicknav.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome-all.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/slick.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
</head>
<body>
<!--? Preloader Start -->
<div id="preloader-active">
    <div class="preloader d-flex align-items-center justify-content-center">
        <div class="preloader-inner position-relative">
            <div class="preloader-circle"></div>
            <div class="preloader-img pere-text">
                <img src="{% static 'assets/img/logo/loder.jpg" alt="">
            </div>
        </div>
    </div>
</div>
<!-- Preloader Start -->
<header>
    <!-- Header Start -->
    <div class="header-area">
        <div class="main-header ">
            <div class="header-top d-none d-lg-block">
                <div class="container">
                    <div class="col-xl-12">
                        <div class="row d-flex justify-content-between align-items-center">
                            <div class="header-info-left">
                                <ul>     
                                    <li>Phone: +99 (0) 101 0000 888</li>
                                    <li>Email: noreply@yourdomain.com</li>
                                </ul>
                            </div>
                            <div class="header-info-right">
                                <ul class="header-social">    
                                    <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                                    <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                                    <li><a href="#"><i class="fab fa-linkedin-in"></i></a></li>
                                    <li> <a href="#"><i class="fab fa-google-plus-g"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="header-bottom  header-sticky">
                <div class="container">
                    <div class="row align-items-center">
                        <!-- Logo -->
                        <div class="col-xl-2 col-lg-2">
                            <div class="logo">
                                <a href="/"><img src="{% static 'assets/img/logo/logo.png' %}" alt=""></a>
                            </div>
                        </div>
                        <div class="col-xl-10 col-lg-10">
                            <div class="menu-wrapper  d-flex align-items-center justify-content-end">
                                <!-- Main-menu -->
                                <div class="main-menu d-none d-lg-block">
                                    <nav> 
                                        <ul id="navigation">                                                                                          
                                            <li><a href="/">Home</a></li>
                                            <li><a href="{% url 'about:about' %}">About</a></li>
                                            <li><a href="{% url 'services:services' %}">Services</a></li>
                                            <li><a href="{% url 'blog:post_list' %}">Our Blog</a></li>
                                            <li><a href="{% url 'contact:contact' %}">Contact</a></li>
                                        </ul>
                                    </nav>
                                </div>
                                <!-- Header-btn -->
                                <div class="header-right-btn d-none d-lg-block ml-20">
                                    <a href="{% url 'contact:contact' %}" class="btn header-btn">Get A Qoue</a>
                                </div>
                            </div>
                        </div> 
                        <!-- Mobile Menu -->
                        <div class="col-12">
                            <div class="mobile_menu d-block d-lg-none"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Header End -->
</header>


{% block body %}
        
{% endblock body %}


<footer>
    <!--? Footer Start-->
    <div class="footer-area footer-bg">
        <div class="container">
            <div class="footer-top footer-padding">
                <!-- footer Heading -->
                <div class="footer-heading">
                    <div class="row justify-content-between">
                        <div class="col-xl-6 col-lg-8 col-md-8">
                            <div class="wantToWork-caption wantToWork-caption2">
                                <h2>We Understand The Importance Approaching Each Work!</h2>
                            </div>
                        </div>
                        <div class="col-xl-3 col-lg-4">
                            <span class="contact-number f-right">+ 1 212-683-9756</span>
                        </div>
                    </div>
                </div>
                <!-- Footer Menu -->
                <div class="row d-flex justify-content-between">
                    <div class="col-xl-2 col-lg-2 col-md-4 col-sm-6">
                        <div class="single-footer-caption mb-50">
                            <div class="footer-tittle">
                                <h4>COMPANY</h4>
                                <ul>
                                    <li><a href="{% url 'about:about' %}">About Us</a></li>
                                    <li><a href="{% url 'contact:contact' %}">Company</a></li>
                                    <li><a href="{% url 'blog:post_list' %}"> Press & Blog</a></li>
                                    <li><a href="#"> Privacy Policy</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-3 col-md-4 col-sm-6">
                        <div class="single-footer-caption mb-50">
                            <div class="footer-tittle">
                                <h4>Open hour</h4>
                                <ul>
                                    <li>Monday 11am-7pm</li>
                                    <li> Tuesday-Friday 11am-8pm</li>
                                    <li> Saturday 10am-6pm</li>
                                    <li> Sunday 11am-6pm</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-2 col-lg-3 col-md-4 col-sm-6">
                        <div class="single-footer-caption mb-50">
                            <div class="footer-tittle">
                                <h4>RESOURCES</h4>
                                <ul>
                                    <li><a href="#">Home Insurance</a></li>
                                    <li><a href="#">Travel Insurance</a></li>
                                    <li><a href="#"> Car Insurance</a></li>
                                    <li><a href="#"> Business Insurance</a></li>
                                    <li><a href="#"> Heal Insurance</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-4 col-md-5 col-sm-6">
                        <div class="single-footer-caption mb-50">
                            <!-- logo -->
                            <div class="footer-logo">
                                <a href="/"><img src="{% static 'assets/img/logo/logo2_footer.png' %}" alt=""></a>
                            </div>
                            <div class="footer-tittle">
                                <div class="footer-pera">
                                    <p class="info1">GThe trade war currently ensuing between te US anfd several natxions around thdhe globe, most fiercely with.</p>
                                </div>
                            </div>
                            <!-- Footer Social -->
                            <div class="footer-social ">
                                <a href="https://www.facebook.com/sai4ull"><i class="fab fa-facebook-f"></i></a>
                                <a href=""><i class="fab fa-twitter"></i></a>
                                <a href="#"><i class="fas fa-globe"></i></a>
                                <a href="#"><i class="fab fa-instagram"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Footer Bottom -->
            <div class="footer-bottom">
                <div class="row d-flex align-items-center">
                    <div class="col-lg-12">
                        <div class="footer-copy-right text-center">
                            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer End-->
</footer>
<!-- Scroll Up -->
<div id="back-top" >
    <a title="Go to Top" href="#"> <i class="fas fa-level-up-alt"></i></a>
</div>

    <!-- JS here -->

    <script src="{% static './assets/js/vendor/modernizr-3.5.0.min.js' %}"></script>
    <!-- Jquery, Popper, Bootstrap -->
    <script src="{% static './assets/js/vendor/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static './assets/js/popper.min.js' %}"></script>
    <script src="{% static './assets/js/bootstrap.min.js' %}"></script>
    <!-- Jquery Mobile Menu -->
    <script src="{% static './assets/js/jquery.slicknav.min.js' %}"></script>

    <!-- Jquery Slick , Owl-Carousel Plugins -->
    <script src="{% static './assets/js/owl.carousel.min.js' %}"></script>
    <script src="{% static './assets/js/slick.min.js' %}"></script>
    <!-- One Page, Animated-HeadLin -->
    <script src="{% static './assets/js/wow.min.js' %}"></script>
    <script src="{% static './assets/js/animated.headline.js' %}"></script>
    <script src="{% static './assets/js/jquery.magnific-popup.js' %}"></script>

    <!-- Nice-select, sticky -->
    <script src="{% static './assets/js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static './assets/js/jquery.sticky.js"></script>
    
    <!-- contact js -->
    <script src="{% static './assets/js/contact.js' %}"></script>
    <script src="{% static './assets/js/jquery.form.js' %}"></script>
    <script src="{% static './assets/js/jquery.validate.min.js' %}"></script>
    <script src="{% static './assets/js/mail-script.js' %}"></script>
    <script src="{% static './assets/js/jquery.ajaxchimp.min.js' %}"></script>
    
    <!-- Jquery Plugins, main Jquery -->	
    <script src="{% static './assets/js/plugins.js' %}"></script>
    <script src="{% static './assets/js/main.js' %}"></script>
    
</body>
</html>